#include "Collections/Generic/EnumerableImplement.h"
#include "Collections/Generic/LinkedListImplement.h"
#include "Collections/Generic/ListImplement.h"
#include "Collections/Array.h"

#ifndef INT_ENUMERABLE_DEFINED
#define INT_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(int)
ENUMERABLE_DEFINE_SELECT(int, int)
ENUMERABLE_DEFINE_SELECTMANY(int, int)
ENUMERABLE_DEFINE_AGGREGATE(int, int)
#endif
#ifndef INT_ARRAY_DEFINED
#define INT_ARRAY_DEFINED
ARRAY_DEFINE(int)
#endif
#ifndef INT_LIST_DEFINED
#define INT_LIST_DEFINED
LIST_DEFINE(int)
#endif
#ifndef INT_LINKED_LIST_DEFINED
#define INT_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(int)
#endif
#ifndef INT_INT_AGGREGATE_DEFINED
#define INT_INT_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(int, int)
#endif


#ifndef INT_EMPTY_CTOR
#define INT_EMPTY_CTOR
DEFINE_EMPTY_VALUE_CTOR(int)
#endif
#ifdef INT_ENUMERABLE_DEFINED
#ifndef INT_ENUMERABLE_IMPLEMENTED
#define INT_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(int)
ENUMERABLE_IMPLEMENT_SELECT(int, int)
ENUMERABLE_IMPLEMENT_SELECTMANY(int, int)
ENUMERABLE_IMPLEMENT_AGGREGATE(int, int)
#endif
#endif
#ifdef INT_ARRAY_DEFINED
#ifndef INT_ARRAY_IMPLEMENTED
#define INT_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(int)
#endif
#endif
#ifdef INT_LIST_DEFINED
#ifndef INT_LIST_IMPLEMENTED
#define INT_LIST_IMPLEMENTED
LIST_IMPLEMENT(int)
#endif
#endif
#ifdef INT_LINKED_LIST_DEFINED
#ifndef INT_LINKED_LIST_IMPLEMENTED
#define INT_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(int)
#endif
#endif