#include "Collections/Generic/EnumerableImplement.h"
#include "Collections/Generic/ListImplement.h"
#include "Collections/Generic/LinkedListImplement.h"
#include "Collections/Array.h"

#ifndef INT_EMPTY_CTOR
#define INT_EMPTY_CTOR
DEFINE_EMPTY_CTOR(int)
#endif
#ifndef INT_ENUMERABLE_DEFINED
#define INT_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(int)
ENUMERABLE_IMPLEMENT(int)
ENUMERABLE_DEFINE_SELECT(int, int)
ENUMERABLE_IMPLEMENT_SELECT(int, int)
ENUMERABLE_DEFINE_SELECTMANY(int, int)
ENUMERABLE_IMPLEMENT_SELECTMANY(int, int)
ENUMERABLE_DEFINE_AGGREGATE(int, int)
ENUMERABLE_IMPLEMENT_AGGREGATE(int, int)
#endif
#ifndef INT_ARRAY_DEFINED
#define INT_ARRAY_DEFINED
ARRAY_DEFINE(int)
ARRAY_IMPLEMENT(int)
#endif
#ifndef INT_LIST_DEFINED
#define INT_LIST_DEFINED
LIST_DEFINE(int)
LIST_IMPLEMENT(int)
#endif
#ifndef INT_LINKED_LIST_DEFINED
#define INT_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(int)
LINKED_LIST_IMPLEMENT(int)
#endif