#include "Collections/Generic/EnumerableImplement.h"
#include "Collections/Generic/LinkedListImplement.h"
#include "Collections/Generic/ListImplement.h"
#include "Collections/Array.h"
#include "Tuple.h"

TUPLE_2_DECLARE(int, int)

#pragma region Int

#ifndef INT_ENUMERABLE_DEFINED
#define INT_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(int)
ENUMERABLE_DEFINE(int_int)
ENUMERABLE_DEFINE_INDEX(int)
ENUMERABLE_DEFINE_SELECT(int, int)
ENUMERABLE_DEFINE_SELECTINDEX(int, int)
ENUMERABLE_DEFINE_SELECTMANY(int, int)
ENUMERABLE_DEFINE_AGGREGATE(int, int)
#endif
#ifndef INT_ARRAY_DEFINED
#define INT_ARRAY_DEFINED
ARRAY_DEFINE(int)
#endif
#ifndef INT_LIST_DEFINED
#define INT_LIST_DEFINED
LIST_DEFINE(int)
#endif
#ifndef INT_LINKED_LIST_DEFINED
#define INT_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(int)
#endif
#ifndef INT_INT_AGGREGATE_DEFINED
#define INT_INT_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(int, int)
#endif


#ifndef INT_EMPTY_CTOR
#define INT_EMPTY_CTOR
DEFINE_EMPTY_VALUE_CTOR(int)
#endif
#ifdef INT_ENUMERABLE_DEFINED
#ifndef INT_ENUMERABLE_IMPLEMENTED
#define INT_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(int)
ENUMERABLE_IMPLEMENT(int_int)
ENUMERABLE_IMPLEMENT_INDEX(int)
ENUMERABLE_IMPLEMENT_SELECT(int, int)
ENUMERABLE_IMPLEMENT_SELECTINDEX(int, int)
ENUMERABLE_IMPLEMENT_SELECTMANY(int, int)
ENUMERABLE_IMPLEMENT_AGGREGATE(int, int)
#endif
#endif
#ifdef INT_ARRAY_DEFINED
#ifndef INT_ARRAY_IMPLEMENTED
#define INT_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(int)
#endif
#endif
#ifdef INT_LIST_DEFINED
#ifndef INT_LIST_IMPLEMENTED
#define INT_LIST_IMPLEMENTED
LIST_IMPLEMENT(int)
#endif
#endif
#ifdef INT_LINKED_LIST_DEFINED
#ifndef INT_LINKED_LIST_IMPLEMENTED
#define INT_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(int)
#endif
#endif

#pragma endregion
#pragma region Float

#ifndef LONG_ENUMERABLE_DEFINED
#define LONG_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(float)
ENUMERABLE_DEFINE_SELECT(float, float)
ENUMERABLE_DEFINE_SELECTINDEX(int, int)
ENUMERABLE_DEFINE_SELECTMANY(float, float)
ENUMERABLE_DEFINE_AGGREGATE(float, float)
#endif
#ifndef LONG_ARRAY_DEFINED
#define LONG_ARRAY_DEFINED
ARRAY_DEFINE(float)
#endif
#ifndef LONG_LIST_DEFINED
#define LONG_LIST_DEFINED
LIST_DEFINE(float)
#endif
#ifndef LONG_LINKED_LIST_DEFINED
#define LONG_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(float)
#endif
#ifndef LONG_LONG_AGGREGATE_DEFINED
#define LONG_LONG_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(float, float)
#endif


#ifndef LONG_EMPTY_CTOR
#define LONG_EMPTY_CTOR
DEFINE_EMPTY_VALUE_CTOR(float)
#endif
#ifdef LONG_ENUMERABLE_DEFINED
#ifndef LONG_ENUMERABLE_IMPLEMENTED
#define LONG_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(float)
ENUMERABLE_IMPLEMENT_SELECT(float, float)
ENUMERABLE_IMPLEMENT_SELECTMANY(float, float)
ENUMERABLE_IMPLEMENT_AGGREGATE(float, float)
#endif
#endif
#ifdef LONG_ARRAY_DEFINED
#ifndef LONG_ARRAY_IMPLEMENTED
#define LONG_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(float)
#endif
#endif
#ifdef LONG_LIST_DEFINED
#ifndef LONG_LIST_IMPLEMENTED
#define LONG_LIST_IMPLEMENTED
LIST_IMPLEMENT(float)
#endif
#endif
#ifdef LONG_LINKED_LIST_DEFINED
#ifndef LONG_LINKED_LIST_IMPLEMENTED
#define LONG_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(float)
#endif
#endif

#pragma endregion
#pragma region Double

#ifndef DOUBLE_ENUMERABLE_DEFINED
#define DOUBLE_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(double)
ENUMERABLE_DEFINE_SELECT(double, double)
ENUMERABLE_DEFINE_SELECTINDEX(int, int)
ENUMERABLE_DEFINE_SELECTMANY(double, double)
ENUMERABLE_DEFINE_AGGREGATE(double, double)
#endif
#ifndef DOUBLE_ARRAY_DEFINED
#define DOUBLE_ARRAY_DEFINED
ARRAY_DEFINE(double)
#endif
#ifndef DOUBLE_LIST_DEFINED
#define DOUBLE_LIST_DEFINED
LIST_DEFINE(double)
#endif
#ifndef DOUBLE_LINKED_LIST_DEFINED
#define DOUBLE_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(double)
#endif
#ifndef DOUBLE_DOUBLE_AGGREGATE_DEFINED
#define DOUBLE_DOUBLE_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(double, double)
#endif


#ifndef DOUBLE_EMPTY_CTOR
#define DOUBLE_EMPTY_CTOR
DEFINE_EMPTY_VALUE_CTOR(double)
#endif
#ifdef DOUBLE_ENUMERABLE_DEFINED
#ifndef DOUBLE_ENUMERABLE_IMPLEMENTED
#define DOUBLE_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(double)
ENUMERABLE_IMPLEMENT_SELECT(double, double)
ENUMERABLE_IMPLEMENT_SELECTMANY(double, double)
ENUMERABLE_IMPLEMENT_AGGREGATE(double, double)
#endif
#endif
#ifdef DOUBLE_ARRAY_DEFINED
#ifndef DOUBLE_ARRAY_IMPLEMENTED
#define DOUBLE_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(double)
#endif
#endif
#ifdef DOUBLE_LIST_DEFINED
#ifndef DOUBLE_LIST_IMPLEMENTED
#define DOUBLE_LIST_IMPLEMENTED
LIST_IMPLEMENT(double)
#endif
#endif
#ifdef DOUBLE_LINKED_LIST_DEFINED
#ifndef DOUBLE_LINKED_LIST_IMPLEMENTED
#define DOUBLE_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(double)
#endif
#endif

#pragma endregion
#pragma region Char

#ifndef CHAR_ENUMERABLE_DEFINED
#define CHAR_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(char)
ENUMERABLE_DEFINE_SELECT(char, char)
ENUMERABLE_DEFINE_SELECTINDEX(int, int)
ENUMERABLE_DEFINE_SELECTMANY(char, char)
ENUMERABLE_DEFINE_AGGREGATE(char, char)
#endif
#ifndef CHAR_ARRAY_DEFINED
#define CHAR_ARRAY_DEFINED
ARRAY_DEFINE(char)
#endif
#ifndef CHAR_LIST_DEFINED
#define CHAR_LIST_DEFINED
LIST_DEFINE(char)
#endif
#ifndef CHAR_LINKED_LIST_DEFINED
#define CHAR_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(char)
#endif
#ifndef CHAR_CHAR_AGGREGATE_DEFINED
#define CHAR_CHAR_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(char, char)
#endif


#ifndef CHAR_EMPTY_CTOR
#define CHAR_EMPTY_CTOR
DEFINE_EMPTY_VALUE_CTOR(char)
#endif
#ifdef CHAR_ENUMERABLE_DEFINED
#ifndef CHAR_ENUMERABLE_IMPLEMENTED
#define CHAR_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(char)
ENUMERABLE_IMPLEMENT_SELECT(char, char)
ENUMERABLE_IMPLEMENT_SELECTMANY(char, char)
ENUMERABLE_IMPLEMENT_AGGREGATE(char, char)
#endif
#endif
#ifdef CHAR_ARRAY_DEFINED
#ifndef CHAR_ARRAY_IMPLEMENTED
#define CHAR_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(char)
#endif
#endif
#ifdef CHAR_LIST_DEFINED
#ifndef CHAR_LIST_IMPLEMENTED
#define CHAR_LIST_IMPLEMENTED
LIST_IMPLEMENT(char)
#endif
#endif
#ifdef CHAR_LINKED_LIST_DEFINED
#ifndef CHAR_LINKED_LIST_IMPLEMENTED
#define CHAR_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(char)
#endif
#endif

#pragma endregion