#include "Collections/Generic/EnumerableImplement.h"
#include "Collections/Generic/LinkedListImplement.h"
#include "Collections/Generic/ListImplement.h"
#include "Collections/Array.h"
#include "Tuple.h"

#pragma region Int

#ifndef INT_ENUMERABLE_DEFINED
#define INT_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(int)
#ifndef INDEX_INT_DEFINED
#define INDEX_INT_DEFINED
TUPLE_2_DEFINE(int, int)
ENUMERABLE_DEFINE(int_int)
ENUMERABLE_DEFINE_INDEX(int)
#endif
ENUMERABLE_DEFINE_SELECT(int, int)
ENUMERABLE_DEFINE_SELECTINDEX(int, int)
ENUMERABLE_DEFINE_SELECTMANY(int, int)
ENUMERABLE_DEFINE_AGGREGATE(int, int)
#endif
#ifndef INT_ARRAY_DEFINED
#define INT_ARRAY_DEFINED
ARRAY_DEFINE(int)
#endif
#ifndef INT_LIST_DEFINED
#define INT_LIST_DEFINED
LIST_DEFINE(int)
#endif
#ifndef INT_LINKED_LIST_DEFINED
#define INT_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(int)
#endif
#ifndef INT_INT_AGGREGATE_DEFINED
#define INT_INT_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(int, int)
#endif


#ifndef INT_EMPTY_CTOR
#define INT_EMPTY_CTOR
IMPLEMENT_EMPTY_VALUE_CTOR(int)
#endif
#ifdef INT_ENUMERABLE_DEFINED
#ifndef INT_ENUMERABLE_IMPLEMENTED
#define INT_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(int)
#ifdef INDEX_INT_DEFINED
#ifndef INDEX_INT_IMPLEMENTED
TUPLE_2_IMPLEMENT(int, int)
ENUMERABLE_IMPLEMENT(int_int)
ENUMERABLE_IMPLEMENT_INDEX(int)
#endif
#endif
ENUMERABLE_IMPLEMENT_SELECT(int, int)
ENUMERABLE_IMPLEMENT_SELECTINDEX(int, int)
ENUMERABLE_IMPLEMENT_SELECTMANY(int, int)
ENUMERABLE_IMPLEMENT_AGGREGATE(int, int)
#endif
#endif
#ifdef INT_ARRAY_DEFINED
#ifndef INT_ARRAY_IMPLEMENTED
#define INT_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(int)
#endif
#endif
#ifdef INT_LIST_DEFINED
#ifndef INT_LIST_IMPLEMENTED
#define INT_LIST_IMPLEMENTED
LIST_IMPLEMENT(int)
#endif
#endif
#ifdef INT_LINKED_LIST_DEFINED
#ifndef INT_LINKED_LIST_IMPLEMENTED
#define INT_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(int)
#endif
#endif

#pragma endregion
#pragma region Float

#ifndef FLOAT_TUPLE_DEFINED
#define FLOAT_TUPLE_DEFINED
TUPLE_2_DEFINE(float, float)
TUPLE_3_DEFINE(float, float, float)
#endif
#ifndef FLOAT_ENUMERABLE_DEFINED
#define FLOAT_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(float)
#ifndef INDEX_FLOAT_DEFINED
#define INDEX_FLOAT_DEFINED
TUPLE_2_DEFINE(int, float)
ENUMERABLE_DEFINE(int_float)
ENUMERABLE_DEFINE_INDEX(float)
#endif
ENUMERABLE_DEFINE_SELECT(float, float)
ENUMERABLE_DEFINE_SELECTINDEX(float, float)
ENUMERABLE_DEFINE_SELECTMANY(float, float)
ENUMERABLE_DEFINE_AGGREGATE(float, float)
#endif
#ifndef FLOAT_ARRAY_DEFINED
#define FLOAT_ARRAY_DEFINED
ARRAY_DEFINE(float)
#endif
#ifndef FLOAT_LIST_DEFINED
#define FLOAT_LIST_DEFINED
LIST_DEFINE(float)
#endif
#ifndef FLOAT_LINKED_LIST_DEFINED
#define FLOAT_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(float)
#endif
#ifndef FLOAT_FLOAT_AGGREGATE_DEFINED
#define FLOAT_FLOAT_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(float, float)
#endif


#ifndef FLOAT_EMPTY_CTOR
#define FLOAT_EMPTY_CTOR
IMPLEMENT_EMPTY_VALUE_CTOR(float)
#endif
#ifdef FLOAT_ENUMERABLE_DEFINED
#ifndef FLOAT_ENUMERABLE_IMPLEMENTED
#define FLOAT_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(float)
#ifdef INDEX_FLOAT_DEFINED
#ifndef INDEX_FLOAT_IMPLEMENTED
TUPLE_2_IMPLEMENT(int, float)
ENUMERABLE_IMPLEMENT(int_float)
ENUMERABLE_IMPLEMENT_INDEX(float)
#endif
#endif
ENUMERABLE_IMPLEMENT_SELECT(float, float)
ENUMERABLE_IMPLEMENT_SELECTINDEX(float, float)
ENUMERABLE_IMPLEMENT_SELECTMANY(float, float)
ENUMERABLE_IMPLEMENT_AGGREGATE(float, float)
#endif
#endif
#ifdef FLOAT_ARRAY_DEFINED
#ifndef FLOAT_ARRAY_IMPLEMENTED
#define FLOAT_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(float)
#endif
#endif
#ifdef FLOAT_LIST_DEFINED
#ifndef FLOAT_LIST_IMPLEMENTED
#define FLOAT_LIST_IMPLEMENTED
LIST_IMPLEMENT(float)
#endif
#endif
#ifdef FLOAT_LINKED_LIST_DEFINED
#ifndef FLOAT_LINKED_LIST_IMPLEMENTED
#define FLOAT_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(float)
#endif
#endif

#pragma endregion
#pragma region Double

#ifndef DOUBLE_ENUMERABLE_DEFINED
#define DOUBLE_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(double)
#ifndef INDEX_DOUBLE_DEFINED
#define INDEX_DOUBLE_DEFINED
TUPLE_2_DEFINE(int, double)
ENUMERABLE_DEFINE(int_double)
ENUMERABLE_DEFINE_INDEX(double)
#endif
ENUMERABLE_DEFINE_SELECT(double, double)
ENUMERABLE_DEFINE_SELECTINDEX(double, double)
ENUMERABLE_DEFINE_SELECTMANY(double, double)
ENUMERABLE_DEFINE_AGGREGATE(double, double)
#endif
#ifndef DOUBLE_ARRAY_DEFINED
#define DOUBLE_ARRAY_DEFINED
ARRAY_DEFINE(double)
#endif
#ifndef DOUBLE_LIST_DEFINED
#define DOUBLE_LIST_DEFINED
LIST_DEFINE(double)
#endif
#ifndef DOUBLE_LINKED_LIST_DEFINED
#define DOUBLE_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(double)
#endif
#ifndef DOUBLE_DOUBLE_AGGREGATE_DEFINED
#define DOUBLE_DOUBLE_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(double, double)
#endif


#ifndef DOUBLE_EMPTY_CTOR
#define DOUBLE_EMPTY_CTOR
IMPLEMENT_EMPTY_VALUE_CTOR(double)
#endif
#ifdef DOUBLE_ENUMERABLE_DEFINED
#ifndef DOUBLE_ENUMERABLE_IMPLEMENTED
#define DOUBLE_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(double)
#ifdef INDEX_DOUBLE_DEFINED
#ifndef INDEX_DOUBLE_IMPLEMENTED
TUPLE_2_IMPLEMENT(int, double)
ENUMERABLE_IMPLEMENT(int_double)
ENUMERABLE_IMPLEMENT_INDEX(double)
#endif
#endif
ENUMERABLE_IMPLEMENT_SELECT(double, double)
ENUMERABLE_IMPLEMENT_SELECTINDEX(double, double)
ENUMERABLE_IMPLEMENT_SELECTMANY(double, double)
ENUMERABLE_IMPLEMENT_AGGREGATE(double, double)
#endif
#endif
#ifdef DOUBLE_ARRAY_DEFINED
#ifndef DOUBLE_ARRAY_IMPLEMENTED
#define DOUBLE_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(double)
#endif
#endif
#ifdef DOUBLE_LIST_DEFINED
#ifndef DOUBLE_LIST_IMPLEMENTED
#define DOUBLE_LIST_IMPLEMENTED
LIST_IMPLEMENT(double)
#endif
#endif
#ifdef DOUBLE_LINKED_LIST_DEFINED
#ifndef DOUBLE_LINKED_LIST_IMPLEMENTED
#define DOUBLE_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(double)
#endif
#endif

#pragma endregion
#pragma region Char

#ifndef CHAR_ENUMERABLE_DEFINED
#define CHAR_ENUMERABLE_DEFINED
ENUMERABLE_DEFINE(char)
#ifndef INDEX_CHAR_DEFINED
#define INDEX_CHAR_DEFINED
TUPLE_2_DEFINE(int, char)
ENUMERABLE_DEFINE(int_char)
ENUMERABLE_DEFINE_INDEX(char)
#endif
ENUMERABLE_DEFINE_SELECT(char, char)
ENUMERABLE_DEFINE_SELECTINDEX(char, char)
ENUMERABLE_DEFINE_SELECTMANY(char, char)
ENUMERABLE_DEFINE_AGGREGATE(char, char)
#endif
#ifndef CHAR_ARRAY_DEFINED
#define CHAR_ARRAY_DEFINED
ARRAY_DEFINE(char)
#endif
#ifndef CHAR_LIST_DEFINED
#define CHAR_LIST_DEFINED
LIST_DEFINE(char)
#endif
#ifndef CHAR_LINKED_LIST_DEFINED
#define CHAR_LINKED_LIST_DEFINED
LINKED_LIST_DEFINE(char)
#endif
#ifndef CHAR_CHAR_AGGREGATE_DEFINED
#define CHAR_CHAR_AGGREGATE_DEFINED
ENUMERABLE_DEFINE_AGGREGATE(char, char)
#endif


#ifndef CHAR_EMPTY_CTOR
#define CHAR_EMPTY_CTOR
IMPLEMENT_EMPTY_VALUE_CTOR(char)
#endif
#ifdef CHAR_ENUMERABLE_DEFINED
#ifndef CHAR_ENUMERABLE_IMPLEMENTED
#define CHAR_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(char)
#ifdef INDEX_CHAR_DEFINED
#ifndef INDEX_CHAR_IMPLEMENTED
TUPLE_2_IMPLEMENT(int, char)
ENUMERABLE_IMPLEMENT(int_char)
ENUMERABLE_IMPLEMENT_INDEX(char)
#endif
#endif
ENUMERABLE_IMPLEMENT_SELECT(char, char)
ENUMERABLE_IMPLEMENT_SELECTINDEX(char, char)
ENUMERABLE_IMPLEMENT_SELECTMANY(char, char)
ENUMERABLE_IMPLEMENT_AGGREGATE(char, char)
#endif
#endif
#ifdef CHAR_ARRAY_DEFINED
#ifndef CHAR_ARRAY_IMPLEMENTED
#define CHAR_ARRAY_IMPLEMENTED
ARRAY_IMPLEMENT(char)
#endif
#endif
#ifdef CHAR_LIST_DEFINED
#ifndef CHAR_LIST_IMPLEMENTED
#define CHAR_LIST_IMPLEMENTED
LIST_IMPLEMENT(char)
#endif
#endif
#ifdef CHAR_LINKED_LIST_DEFINED
#ifndef CHAR_LINKED_LIST_IMPLEMENTED
#define CHAR_LINKED_LIST_IMPLEMENTED
LINKED_LIST_IMPLEMENT(char)
#endif
#endif

#pragma endregion