#include "Collections/Generic/EnumerableImplement.h"
#include "Collections/Generic/ListImplement.h"
#include "Text/String.h"

#ifdef STRING_ENUMERABLE_DEFINED
#ifndef STRING_ENUMERABLE_IMPLEMENTED
#define STRING_ENUMERABLE_IMPLEMENTED
ENUMERABLE_IMPLEMENT(string)
ENUMERABLE_IMPLEMENT_SELECT(string, string)
ENUMERABLE_IMPLEMENT_SELECTMANY(string, string)
ENUMERABLE_IMPLEMENT_AGGREGATE(string, string)
#endif
#endif
#ifdef STRING_LIST_DEFINED
#ifndef STRING_LIST_IMPLEMENTED
#define STRING_LIST_IMPLEMENTED
LIST_IMPLEMENT(string)
#endif
#endif
#ifdef STRING_INT_AGGREGATE_DEFINED
#ifndef STRING_INT_AGGREGATE_IMPLEMENTED
#define STRING_INT_AGGREGATE_IMPLEMENTED
ENUMERABLE_IMPLEMENT_AGGREGATE(string, int)
#endif
#endif